#==========================================================
#= GestUser Web Service - Versione Base
#==========================================================

server:
  port: 8019
spring:
  application:
    name: GestUser
#==========================================================
#= PARAMETRI DB MONGODB 
#==========================================================
