#==========================================================
#= Articoli Web Service - Versione Base
#==========================================================

server:
  port: 8080
  
spring:
  application:
    name: PrenotazioneWebService
#==========================================================
#= PARAMETRI DBMS POSTGRESQL 
#==========================================================
  sql:
    init:
      mode: always
      platform: all
  datasource:
    password: ""
    url: jdbc:mariadb://localhost:3306/reservation
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        jdbc:
    show-sql: true
#==========================================================
#Opzioni Accesso Servizio gestuser
#==========================================================

GestUser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  password: asdfgh
  
  # ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    header: Authorization
    secret: $123_Stella@xantrix.it
    
# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    org.springframework.security: DEBUG
