#==========================================================
#= Articoli Web Service - Versione Base
#==========================================================

server:
  port: 8081
  
spring:
  application:
    name: PrenotazioneWebService
  main:
    allow-circular-references: true
#==========================================================
#= PARAMETRI DBMS POSTGRESQL 
#==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: foxmulder
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
    show-sql: true
#==========================================================
#Opzioni Accesso Servizio gestuser
#==========================================================

GestUser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  password: asdfgh
  
  # ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    header: Authorization
    secret: $123_Stella@xantrix.it
    
# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    org.springframework.security: DEBUG
